### ISSUE TITLE
PBEggs are not being processed when semantics are given to symbols

### ISSUE THREAD

**Issue by x64Eddie** [Parabeac/parabeac_core#8]
When giving a _semantic_ to a symbol in sketch that correlates to a PBEgg, the PBEgg is not being processed. There is no output for that specific symbol in the code generation phase.

**Comment by Ihuds577** [comment]
Eddie How's this issue going? Do you need any help? 😉

**Comment by siliconivan** [comment]
I believe this is done, closing it out.
